export default {
  up: (queryInterface, Sequelize) => {
    return queryInterface.bulkInsert(
      'Tasks',
      [
        {
          id: 1,
          goal_id: 1,
          title: 'Have a career conversation with your direct reports',
          description: '',
          duration: 90,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 2,
          goal_id: 1,
          title: 'Solicit feedback from your direct reports',
          description: '',
          duration: 30,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 3,
          goal_id: 1,
          title: 'Meet with your skip-level reports',
          description: '',
          duration: 120,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 4,
          goal_id: 1,
          title: 'Schedule a regular 1:1 meeting with all your direct reports',
          description: '',
          duration: 30,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 5,
          goal_id: 1,
          title: 'Delegate something you currently do to your direct report',
          description: '',
          duration: 60,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 6,
          goal_id: 2,
          title:
            'Make a list of influential people in your field at your company, and outside of your company',
          description: '',
          duration: 30,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 7,
          goal_id: 2,
          title:
            'Invite someone in a different department for a "Get To Know You" coffee or lunch',
          description: '',
          duration: 60,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 8,
          goal_id: 2,
          title: 'Attend an industry networking event',
          description: '',
          duration: 90,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 9,
          goal_id: 2,
          title: 'Join your local college/university alumni group',
          description: '',
          duration: 30,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 10,
          goal_id: 3,
          title: 'Have a career conversation with your manager',
          description: '',
          duration: 60,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 11,
          goal_id: 3,
          title: 'Ask for peer feedback',
          description: '',
          duration: 60,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 12,
          goal_id: 3,
          title:
            'Set up a career lunch with someone at a higher level besides your manager',
          description: '',
          duration: 60,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 13,
          goal_id: 3,
          title: 'Draft a list of OKRs for yourself for the next 3 months',
          description: '',
          duration: 60,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 14,
          goal_id: 4,
          title: 'Write your personal brand statement',
          description: '',
          duration: 30,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 15,
          goal_id: 4,
          title: 'Draft a blog post on an area of expertise',
          description: '',
          duration: 90,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 16,
          goal_id: 4,
          title: 'Make a list of 5 books to read that will help you grow',
          description: '',
          duration: 60,
          created_at: new Date(),
          updated_at: new Date(),
        },
      ],
      {},
    );
  },

  down: (queryInterface, Sequelize) => {
    return queryInterface.bulkDelete('Tasks', null, {});
  },
};
